### ISSUE TITLE
Test Framework

### ISSUE THREAD

**Issue by oscarbranson** [PalaeoCarb/Kgen#14]
Each language should have a GitHub action to test calculated K values against 'best practices' check values, and Mg and Ca correction factors against MyAMI_V1 check values.

The output of each language should be checked against the other two.

## Python
- [x] Test against 'best practices' Ks
- [x] Test against MyAMI_V1 **Handled in pymyami module**
- [x] GitHub Action
- [x] Passing Tests

## MATLAB
- [x] Test against 'best practices' Ks
- [x] (Test against MyAMI_V1 - maybe cross-comparison below is enough?)
- [x] GitHub Action
- [x] Passing Tests

## R
- [x] Test against 'best practices' Ks
- [x] Test against MyAMI_V1 **Directly imports pymyami, where this is already checked**
- [x] GitHub Action
- [x] Passing Tests

## Cross Checking
 - [x] Calculate values in each language
 - [x] Output to text files
 - [x] Compare outputs of each language to the other two.
- [x] Passing Tests
- [x] Action to check that K coefficients are the same in all languages

**Comment by rossidae** [comment]
For MyAMI - Matlab is (currently) using the polynomial for correction factors. Is that sufficient accuracy etc. to consider it validated?

**Comment by dm807cam** [comment]
New PR includes a test routine that compares calculated Ks with check values. If I find some time, I will also set this up for the pressure correction soon.

**Comment by rossidae** [comment]
Test framework in place and at present all languages agree
