### ISSUE TITLE
pH Scales

### ISSUE THREAD

**Issue by oscarbranson** [PalaeoCarb/Kgen#15]
## What pH scale do we use?

At present all use the 'Best Practices' coefficients. This means that all are on the Total scale, except:

## KS 
Free Scale (corrected for seawater density). **THIS IS FINE**

## KSi, KP1, KP2, KP3, KW
Footnote 5: "0.015 has been subtracted from the constant term in each of these expressions: (49), (52), (55) to convert—approximately—from the SWS pH scale (including HF) used by Millero (1995) to the “total” hydrogen ion scale used here."

## HF
Is on the Free *and* Total Scale?!

## pH Scales
pH_free = -log10(H_free)
pH_total = -log10(H_free + HSO4) = -log10(H_total)
pH_SWS = -log10(H_free + HSO4 + HF) = -log10(H_SWS)

## Pressure Correction
Is on SWS? Maybe? What should it be?

Some of the original work by Pytkowicz is on the NBS scale.

**Comment by rossidae** [comment]
Changing all equilibrium constants onto the free scale seems desirable in the long term, but at the moment we've converged on the total scale for both modern, surface K's and MyAMI correction factors - leaving only the pressure correction on (we think) the seawater scale.

Interim solution is to set up a test to work out the error introduced by using pressure correction coefficients as if they are on the total scale.

**Comment by rossidae** [comment]
Sticking with the total scale for now at least.
