### ISSUE TITLE
Adjust K's for secular evolution of seawater calcium and magnesium

### ISSUE THREAD

**Issue by rossidae** [PalaeoCarb/Kgen#5]
- [x] Cross-checking MyAIM_V2 against [seacarbx](url) LUT
- [x] Script to generate MyAMI LUT for use by all packages.
- [x] Agree on shared form of user-facing Kgen function for K calculation and adjustment.
- [x] Python Kgen
   - [x] K calculation framework.
   - [x] MyAMI direct Fcorr calculation using refactored MyAMI
   - [x] MyAMI Fcorr approximation using polynomial function
   - [x] User-facing master function for K calculation and adjustment 
- [x] MATLAB Kgen
   - [x] K calculation framework.
   - [x] MyAMI Fcorr approximation using polynomial function
   - [x] User-facing master function for K calculation and adjustment 
- [x] R Kgen
   - [x] K calculation framework.
   - [x] MyAMI Fcorr approximation using polynomial function
   - [x] User-facing master function for K calculation and adjustment 
- [x] Automate testing cross-checking of different implementations.

**Comment by dm807cam** [comment]
I believe recent PRs covered all points listed under R Kgen and can be marked completed.

**Comment by rossidae** [comment]
Will test the time advantage of having a polynomial implementation in Matlab vs running it through the python linkage.
