### ISSUE TITLE
Pymyami version checks

### ISSUE THREAD

**Issue by dm807cam** [PalaeoCarb/Kgen#51]
Add a check in Kgen for R that checks local pymyami version number against version number specified in the package and update  pymyami if numbers mismatch.  

Check if there is an option to specify python packages in the DESCRIPTION file as can be done for Rcpp.

**Comment by oscarbranson** [comment]
don't think we need this - pymyami version updates are handled by update_pymyami.py script?

**Comment by dm807cam** [comment]
We still need a way for Ken to check what version of pymyami is installed on the user's system. If we specify v3, we need to make sure that v3 is also installed. This check needs to run every time a Kgen function is called to ensure that a version of Kgen always uses a certain version of pymyami
